export type SparkColour =
	| 'blueDark'
	| 'blue'
	| 'blueLight'
	| 'violetDark'
	| 'violet'
	| 'violetLight'
	| 'purpleDark'
	| 'purple'
	| 'purpleLight'
	| 'magenta'
	| 'magentaDark'
	| 'magentaLight'
	| 'hotPink'
	| 'orange'
	| 'tangerine'
	| 'yellow'
	| 'lime'
	| 'turquoise'
	| 'grey'
	| 'greyLight'
	| 'greyMidDark'
	| 'greyDark'
	| 'successGreen'
	| 'failureRed'
	| 'primaryText'
	| 'secondaryText';

export const colours: { [colour in SparkColour]: string } = {
	blueDark: '#0a71a2',
	blue: '#0d8dca',
	blueLight: '#3da4df',
	violetDark: '#2a2567',
	violet: '#342e81',
	violetLight: '#5d589a',
	purpleDark: '#7a1e68',
	purple: '#982682',
	purpleLight: '#ad519b',
	magenta: '#df2080',
	magentaDark: '#c50063',
	magentaLight: '#ff52a9',
	hotPink: '#e64172',
	orange: '#ea6660',
	tangerine: '#ef9222',
	yellow: '#fee801',
	lime: '#afc85b',
	turquoise: '#00a78e',
	grey: '#e9e8e8',
	greyLight: '#f4f4f4',
	greyMidDark: '#eeeeee',
	greyDark: '#646568',
	successGreen: '#3bab28',
	failureRed: '#e91c1c',
	primaryText: '#2f1a45',
	secondaryText: '#646569',
};
